[project]
name = "milc"
version = "1.9.1"
description = "Batteries-Included Python 3 CLI Framework (local fork)"
requires-python = ">=3.7"
dependencies = [
    "argcomplete",
    "colorama",
    "halo",
    "platformdirs",
    "spinners",
    "types-colorama",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["milc*"]
